# Generated by Django 6.0.1 on 2026-02-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
