# Generated by Django 6.0.1 on 2026-03-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
